services:
  node:
    build:
      dockerfile: Containerfile
      network: host
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.wengerdev.rule=Host(`wenger.dev`)
      - traefik.http.routers.wengerdev.entryPoints=https
      - traefik.http.routers.wengerdev.tls=true
      - traefik.http.routers.wengerdev.tls.certresolver=cloudflare
      - traefik.http.routers.wengerdev.service=wengerdev
      - traefik.http.services.wengerdev.loadbalancer.server.port=80

networks:
  default:
    external: true
    name: private
